sprite $cue_logo [64x64/16z] {
fLUBbYen22Eyxl__yNLoy5G7PnPhzhqQIA3J5ha2r2FoWGXNo1Z5pNzlIDSnc-IET8pOKU-dSdUwg7_5do9GxF0Jdl-_r-2bz05Je6Ag-GFbocwJ5zjQ6iR8
MmcQnRvmUKHW0ltySlc-4MXL1xsYkzyt2IN1hkZzXIxXamAbzT31-lWK07c8elPXW8Iy82WUCeB64I1EvgjjSmMsrBDn9cEOnwk3uBAHBq01JuOkyrE00R3I
B_LJ1ra2AhryYIN0QtVQ5P0xwGLiGScd-nq3IldX-9wlDB0ddpWCXE2JV4mD9BHNt-815K79SeW7yPR7M01l1mEheQcYKVzG2GFH2c1nBfz7RQPlVBtee9Cl
BqYKl14_pkKdYNZNBntVy3CEw9I_dn-9OW7TV-Ut-bKgpGh57zVrQ_q3ZpSSOIYCtyCk-DxN3oBSWmGFTwgh-dbVFslzBa0Lfzy0eg_VzVnixc1im2u_Vjy_
TCz0sHV1fW5sxlVz-_VpGxW4TIDzY6mAGEt-kmUeh_GKyAK3yoZt5OuEi7L_8QRNBmBj_iHJACqnhrsYNJ_J0nFnbi_Qzm0wy4wplINh0hnpVrxtTxrD7elU
0zpF3_gSGFGgV9O4DpJbvfKySMDl3L-ca0BKrlpaa-al-_oMmmdmw6x5YAAIEsENXeOncu35UNuEWunHDOjCZi6hbXt_0G
}