sprite $cue_logo [64x64/16z] {
fTVfTlCg38NXvej1xnROkl-xFJLePKuQh_FywhGbuO6IUDABGnNYGiYGbnv_Qe5jlAB0_xNuQ3MPUAkPR8tt429PhMKPIZKZ2H5lz4fariflh9GwbBASbsfC
_x0jNl5swJnw8jH-WR1zbieWkkB99jLBUWzt0Fy5q3L_pc3kZoEuEB6hIwaeG44a_ZcisYiOko9jZzqRW9Mb8iER7kgxgBAI8mJt1SICByLaM8jd6yQYkXG3
-97VJN_AsN54l85mopLKlnRehSnu9I0-WA3C0lQpHgfaN8RY8wcI1R2O66ofeXD_u590chrMnOnZtUDFKh5bhhVr-9Mtj10GNu1kUHk9Y2QDnPjGV0MyZXKq
zT4_5qzyQOwxisW8g0LJV8smCS2gpGwrJw0SmBoFrMF40Ppd05KesxU8umD8ZF4jF8xetkhP04fUp1Q756C-0pc-Y8Gxe5Lj5z5xk_MmW6sElteapZY0SPTt
Jv4qdw6y-KJgXIG4HBXpAv9-vXqOUK5CPf0CREODK8hKZUpFSjCVeCsmBldX8GygbM6fKYI60F3dl7jSe5B8VFERVFCjmiouo-ifJ-Rj8R_rtA-l-IJNNNvv
cVUzVtFfBZ_kOc-t-JVp0y4akMUUFTxxwxo8X6RQk6M0JzTyNlzP9vxlFo8jW3_TFqfzVdxwYTI4U1RfP7Rx_Fv48d1oP1nWPVMhI5f7Fb__ThCk5q0ZGWAG
Nhn_7SttHta1FGvHFdvdomjuCDzgxX-vWExReJZA_Uko08i3ScWa_ydz-r1UVLvza_6__d-egyq1Yex4H_kHEJu0D-zEHFCvW7rRO2EV7SvQ8yBPbQyBW6xF
3z7R0h0K2dmPBm1MjjX9ccT73FuUVikDQrL_F81HeCS7WCZZ5qHQJtOzVbgyHo2RSOouSBVByHVur3tFht3UuifL0COl6oyNqG0VC-uiz7WgpDjOJ0jUYLlT
EtGkvtUJuixgRkG8rTH0Sc8WN5HXUt66K3pA0f2VNto1PAF09IqxAvvvGGnMpgLMosyrFpwTCqs7BLv2nZ02IobfVWPaCX7lgD58PhMMKQMQ6Ud4qkEzZbXv
Qq4v-rlTX8aNP7YcFzfCWWOY2Vs0f7Zs7m
}
